version: '3.9'

services:
  mongodb-data:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./db/:/data/db
    networks:
      backend:
        aliases:
          - "mongodb-data"

  service-backend:
    depends_on:
      - mongodb-data
    container_name: service-caseStudy
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8088:8080"
    networks:
      backend:
        aliases:
          - "service-backend"
networks:
  backend:
    driver: bridge